### ISSUE TITLE
无法正确同步删除文件目录

### ISSUE THREAD

**Issue by Lumysia** [dr34m-cn/taosync#42]
## 问题描述

本地只读(对Alist)目录`/WebDisk`正常向多网盘同步成功后，本地删除`/WebDisk/Test`目录，再次手动扫描同步目标结束后显示`无需同步`，检查并确认多个目标网盘没有任何网盘删除`/WebDisk/Test`目录，检查Alist日志后确认没有任何执行日志。

Edit: 
 - 空的多余目录不会被自动删除
 - 存在于排除项中的文件夹在目标目录中不会被删除，排除项同时应用于来源目录和目标目录？请问可以提供选择吗？

## TaoSync配置

- 引擎：`http://alist:5244` (工作正常)
- 作业：
  - 来源：`/Local_DSM/WebDisk/`
  - 目标：`/CN_123/WebDisk/` `/CN_189/WebDisk/` `/CN_Aliyun/WebDisk/` `/CN_Quark/WebDisk/`
  - 同步方式: `全同步`
  - 同步速度: `标准`
  - 排除项规则: `@eaDir` `/Private` `/Global`

## 系统环境

- Synology DSM 7.2.2 Container Station
- `dr34m/tao-sync:latest` - `sha256:048e4cb6bc9eae867e1e2a9018f2246067fcd4bd8eb2b884d9dfa9c7e68a118e` - `v0.2.3`

## Compose

```yml
version: "3"
services:
  alist:
    image: xhofe/alist-aria2:latest
    networks:
      alist_network:
    ports:
      - 127.0.0.1:5244:5244
    restart: unless-stopped
    volumes:
      - ${DATA_PATH}/alist:/opt/alist/data
      - ${WEBDISK_LOCAL_PATH}:/opt/alist/local-dsm/WebDisk:ro
    environment:
      PUID: 0
      PGID: 0
      UMASK: 022

  taosync:
    image: dr34m/tao-sync:latest
    networks:
      alist_network:
    ports:
      - 127.0.0.1:8023:8023
    restart: unless-stopped
    volumes:
      - ${DATA_PATH}/taosync:/app/data

networks:
  alist_network:
```
